# TODO: make log "description" -> should create dir YYYY-MM-dd with notes.md,
# add project name as first search tag
# inside
# TODO: make find-log "prompt" -> should search through all note.md files and
# open result dir if it only one, or show results with less
